# Generated by Django 4.2.2 on 2023-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('registro', models.CharField(max_length=50)),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor')], default=1, max_length=1)),
            ],
        ),
    ]
