# Generated by Django 4.2.2 on 2023-06-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_grupo',
        ),
    ]
