# Generated by Django 4.2.2 on 2023-06-22 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_id_professor'),
        ('users', '0004_remove_user_id_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_grupo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
