# Generated by Django 4.2.2 on 2023-06-25 17:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_image_user),
        ),
    ]
