# Generated by Django 4.2.2 on 2023-06-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_img_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
        migrations.AddField(
            model_name='user',
            name='bulk_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
