# Generated by Django 4.2.2 on 2023-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_senha_user_bulk_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bulk_file',
        ),
    ]
