# Generated by Django 4.2.2 on 2023-06-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bulkusers_remove_user_bulk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkusers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
