# Generated by Django 4.2.2 on 2023-06-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_bulkusers_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkUsers',
        ),
    ]
