# Generated by Django 4.2.2 on 2023-06-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_img_group'),
        ('users', '0013_delete_bulkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='groups.group'),
        ),
    ]
