# Generated by Django 4.2.2 on 2023-06-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_id_professor'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='data',
            new_name='dataEntrega',
        ),
    ]
