# Generated by Django 4.2.2 on 2023-06-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_rename_timeline_task_rename_data_task_dataentrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='task',
            name='entrege',
            field=models.BooleanField(default=False),
        ),
    ]
