# Generated by Django 4.2.2 on 2023-06-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_rename_nome_task_titulo_task_entrege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='entrege',
            new_name='entregue',
        ),
    ]
