# Generated by Django 4.2.2 on 2023-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id_professor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
