# Generated by Django 4.2.2 on 2023-06-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_grupo_alter_user_tipo_usuario'),
        ('groups', '0002_group_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
