# Generated by Django 4.2.2 on 2023-06-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_id_grupo'),
        ('groups', '0003_group_aprovado_alter_group_id_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
