# Generated by Django 4.2.2 on 2023-06-26 16:31

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_id_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img_group',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.upload_image_group),
        ),
    ]
