# Generated by Django 4.2.2 on 2023-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_img_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
    ]
